/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedOrganizationsOrgIdRouteImport } from './routes/_authenticated/organizations/$orgId'
import { Route as AuthenticatedOrganizationsOrgIdIndexRouteImport } from './routes/_authenticated/organizations/$orgId/index'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/index'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/triage'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/tasks'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/settings'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/docs'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/conversations/index'
import { Route as AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRouteImport } from './routes/_authenticated/organizations/$orgId/projects/$projectId/conversations/$conversationId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRoute =
  AuthenticatedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdIndexRoute =
  AuthenticatedOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRouteImport.update({
    id: '/triage',
    path: '/triage',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRouteImport.update({
    id: '/docs',
    path: '/docs',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRouteImport.update(
    {
      id: '/conversations/',
      path: '/conversations/',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRouteImport.update(
    {
      id: '/conversations/$conversationId',
      path: '/conversations/$conversationId',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/organizations/$orgId/': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/organizations/$orgId/projects/$projectId': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteWithChildren
  '/organizations/$orgId/projects/$projectId/docs': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute
  '/organizations/$orgId/projects/$projectId/settings': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute
  '/organizations/$orgId/projects/$projectId/tasks': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute
  '/organizations/$orgId/projects/$projectId/triage': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute
  '/organizations/$orgId/projects/$projectId/': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute
  '/organizations/$orgId/projects/$projectId/conversations/$conversationId': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute
  '/organizations/$orgId/projects/$projectId/conversations/': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/organizations/$orgId/projects/$projectId/docs': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute
  '/organizations/$orgId/projects/$projectId/settings': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute
  '/organizations/$orgId/projects/$projectId/tasks': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute
  '/organizations/$orgId/projects/$projectId/triage': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute
  '/organizations/$orgId/projects/$projectId': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute
  '/organizations/$orgId/projects/$projectId/conversations/$conversationId': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute
  '/organizations/$orgId/projects/$projectId/conversations': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/organizations/$orgId/': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/_authenticated/organizations/$orgId/projects/$projectId': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteWithChildren
  '/_authenticated/organizations/$orgId/projects/$projectId/docs': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute
  '/_authenticated/organizations/$orgId/projects/$projectId/settings': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute
  '/_authenticated/organizations/$orgId/projects/$projectId/tasks': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute
  '/_authenticated/organizations/$orgId/projects/$projectId/triage': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute
  '/_authenticated/organizations/$orgId/projects/$projectId/': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute
  '/_authenticated/organizations/$orgId/projects/$projectId/conversations/$conversationId': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute
  '/_authenticated/organizations/$orgId/projects/$projectId/conversations/': typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/ai'
    | '/dashboard'
    | '/organizations/$orgId'
    | '/organizations/'
    | '/organizations/$orgId/'
    | '/organizations/$orgId/projects/$projectId'
    | '/organizations/$orgId/projects/$projectId/docs'
    | '/organizations/$orgId/projects/$projectId/settings'
    | '/organizations/$orgId/projects/$projectId/tasks'
    | '/organizations/$orgId/projects/$projectId/triage'
    | '/organizations/$orgId/projects/$projectId/'
    | '/organizations/$orgId/projects/$projectId/conversations/$conversationId'
    | '/organizations/$orgId/projects/$projectId/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/ai'
    | '/dashboard'
    | '/organizations'
    | '/organizations/$orgId'
    | '/organizations/$orgId/projects/$projectId/docs'
    | '/organizations/$orgId/projects/$projectId/settings'
    | '/organizations/$orgId/projects/$projectId/tasks'
    | '/organizations/$orgId/projects/$projectId/triage'
    | '/organizations/$orgId/projects/$projectId'
    | '/organizations/$orgId/projects/$projectId/conversations/$conversationId'
    | '/organizations/$orgId/projects/$projectId/conversations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/organizations/'
    | '/_authenticated/organizations/$orgId/'
    | '/_authenticated/organizations/$orgId/projects/$projectId'
    | '/_authenticated/organizations/$orgId/projects/$projectId/docs'
    | '/_authenticated/organizations/$orgId/projects/$projectId/settings'
    | '/_authenticated/organizations/$orgId/projects/$projectId/tasks'
    | '/_authenticated/organizations/$orgId/projects/$projectId/triage'
    | '/_authenticated/organizations/$orgId/projects/$projectId/'
    | '/_authenticated/organizations/$orgId/projects/$projectId/conversations/$conversationId'
    | '/_authenticated/organizations/$orgId/projects/$projectId/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId/': {
      id: '/_authenticated/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/organizations/$orgId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/'
      path: '/'
      fullPath: '/organizations/$orgId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/triage': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/triage'
      path: '/triage'
      fullPath: '/organizations/$orgId/projects/$projectId/triage'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/tasks': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/organizations/$orgId/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/settings': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/organizations/$orgId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/docs': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/docs'
      path: '/docs'
      fullPath: '/organizations/$orgId/projects/$projectId/docs'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/conversations/': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/conversations/'
      path: '/conversations'
      fullPath: '/organizations/$orgId/projects/$projectId/conversations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
    '/_authenticated/organizations/$orgId/projects/$projectId/conversations/$conversationId': {
      id: '/_authenticated/organizations/$orgId/projects/$projectId/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/organizations/$orgId/projects/$projectId/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteChildren {
  AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute
}

const AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteChildren: AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdDocsRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdSettingsRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdTasksRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdTriageRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdIndexRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsConversationIdRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdConversationsIndexRoute,
  }

const AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteWithChildren =
  AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteChildren,
  )

interface AuthenticatedOrganizationsOrgIdRouteChildren {
  AuthenticatedOrganizationsOrgIdIndexRoute: typeof AuthenticatedOrganizationsOrgIdIndexRoute
  AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute: typeof AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteWithChildren
}

const AuthenticatedOrganizationsOrgIdRouteChildren: AuthenticatedOrganizationsOrgIdRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdIndexRoute:
      AuthenticatedOrganizationsOrgIdIndexRoute,
    AuthenticatedOrganizationsOrgIdProjectsProjectIdRoute:
      AuthenticatedOrganizationsOrgIdProjectsProjectIdRouteWithChildren,
  }

const AuthenticatedOrganizationsOrgIdRouteWithChildren =
  AuthenticatedOrganizationsOrgIdRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationsOrgIdRoute: typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationsOrgIdRoute:
    AuthenticatedOrganizationsOrgIdRouteWithChildren,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
