/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedOrgSlugRouteImport } from './routes/_authenticated/$orgSlug'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedOrgSlugIndexRouteImport } from './routes/_authenticated/$orgSlug/index'
import { Route as AuthenticatedOrgSlugMyTasksRouteImport } from './routes/_authenticated/$orgSlug/my-tasks'
import { Route as AuthenticatedOrgSlugProjectsProjectIdRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId'
import { Route as AuthenticatedOrgSlugProjectsProjectIdIndexRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/index'
import { Route as AuthenticatedOrgSlugProjectsProjectIdTriageRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/triage'
import { Route as AuthenticatedOrgSlugProjectsProjectIdTasksRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/tasks'
import { Route as AuthenticatedOrgSlugProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/settings'
import { Route as AuthenticatedOrgSlugProjectsProjectIdDocsRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/docs'
import { Route as AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/conversations/index'
import { Route as AuthenticatedOrgSlugProjectsProjectIdConversationsNewRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/conversations/new'
import { Route as AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRouteImport } from './routes/_authenticated/$orgSlug/projects/$projectId/conversations/$conversationId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgSlugRoute = AuthenticatedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgSlugIndexRoute =
  AuthenticatedOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugMyTasksRoute =
  AuthenticatedOrgSlugMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdRoute =
  AuthenticatedOrgSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdIndexRoute =
  AuthenticatedOrgSlugProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdTriageRoute =
  AuthenticatedOrgSlugProjectsProjectIdTriageRouteImport.update({
    id: '/triage',
    path: '/triage',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdTasksRoute =
  AuthenticatedOrgSlugProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdSettingsRoute =
  AuthenticatedOrgSlugProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdDocsRoute =
  AuthenticatedOrgSlugProjectsProjectIdDocsRouteImport.update({
    id: '/docs',
    path: '/docs',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute =
  AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute =
  AuthenticatedOrgSlugProjectsProjectIdConversationsNewRouteImport.update({
    id: '/conversations/new',
    path: '/conversations/new',
    getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
  } as any)
const AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute =
  AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRouteImport.update(
    {
      id: '/conversations/$conversationId',
      path: '/conversations/$conversationId',
      getParentRoute: () => AuthenticatedOrgSlugProjectsProjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/$orgSlug/my-tasks': typeof AuthenticatedOrgSlugMyTasksRoute
  '/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/$orgSlug/projects/$projectId': typeof AuthenticatedOrgSlugProjectsProjectIdRouteWithChildren
  '/$orgSlug/projects/$projectId/docs': typeof AuthenticatedOrgSlugProjectsProjectIdDocsRoute
  '/$orgSlug/projects/$projectId/settings': typeof AuthenticatedOrgSlugProjectsProjectIdSettingsRoute
  '/$orgSlug/projects/$projectId/tasks': typeof AuthenticatedOrgSlugProjectsProjectIdTasksRoute
  '/$orgSlug/projects/$projectId/triage': typeof AuthenticatedOrgSlugProjectsProjectIdTriageRoute
  '/$orgSlug/projects/$projectId/': typeof AuthenticatedOrgSlugProjectsProjectIdIndexRoute
  '/$orgSlug/projects/$projectId/conversations/$conversationId': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute
  '/$orgSlug/projects/$projectId/conversations/new': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute
  '/$orgSlug/projects/$projectId/conversations/': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/$orgSlug/my-tasks': typeof AuthenticatedOrgSlugMyTasksRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/$orgSlug/projects/$projectId/docs': typeof AuthenticatedOrgSlugProjectsProjectIdDocsRoute
  '/$orgSlug/projects/$projectId/settings': typeof AuthenticatedOrgSlugProjectsProjectIdSettingsRoute
  '/$orgSlug/projects/$projectId/tasks': typeof AuthenticatedOrgSlugProjectsProjectIdTasksRoute
  '/$orgSlug/projects/$projectId/triage': typeof AuthenticatedOrgSlugProjectsProjectIdTriageRoute
  '/$orgSlug/projects/$projectId': typeof AuthenticatedOrgSlugProjectsProjectIdIndexRoute
  '/$orgSlug/projects/$projectId/conversations/$conversationId': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute
  '/$orgSlug/projects/$projectId/conversations/new': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute
  '/$orgSlug/projects/$projectId/conversations': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/$orgSlug/my-tasks': typeof AuthenticatedOrgSlugMyTasksRoute
  '/_authenticated/$orgSlug/': typeof AuthenticatedOrgSlugIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/$orgSlug/projects/$projectId': typeof AuthenticatedOrgSlugProjectsProjectIdRouteWithChildren
  '/_authenticated/$orgSlug/projects/$projectId/docs': typeof AuthenticatedOrgSlugProjectsProjectIdDocsRoute
  '/_authenticated/$orgSlug/projects/$projectId/settings': typeof AuthenticatedOrgSlugProjectsProjectIdSettingsRoute
  '/_authenticated/$orgSlug/projects/$projectId/tasks': typeof AuthenticatedOrgSlugProjectsProjectIdTasksRoute
  '/_authenticated/$orgSlug/projects/$projectId/triage': typeof AuthenticatedOrgSlugProjectsProjectIdTriageRoute
  '/_authenticated/$orgSlug/projects/$projectId/': typeof AuthenticatedOrgSlugProjectsProjectIdIndexRoute
  '/_authenticated/$orgSlug/projects/$projectId/conversations/$conversationId': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute
  '/_authenticated/$orgSlug/projects/$projectId/conversations/new': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute
  '/_authenticated/$orgSlug/projects/$projectId/conversations/': typeof AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/$orgSlug'
    | '/ai'
    | '/dashboard'
    | '/$orgSlug/my-tasks'
    | '/$orgSlug/'
    | '/organizations/'
    | '/$orgSlug/projects/$projectId'
    | '/$orgSlug/projects/$projectId/docs'
    | '/$orgSlug/projects/$projectId/settings'
    | '/$orgSlug/projects/$projectId/tasks'
    | '/$orgSlug/projects/$projectId/triage'
    | '/$orgSlug/projects/$projectId/'
    | '/$orgSlug/projects/$projectId/conversations/$conversationId'
    | '/$orgSlug/projects/$projectId/conversations/new'
    | '/$orgSlug/projects/$projectId/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/ai'
    | '/dashboard'
    | '/$orgSlug/my-tasks'
    | '/$orgSlug'
    | '/organizations'
    | '/$orgSlug/projects/$projectId/docs'
    | '/$orgSlug/projects/$projectId/settings'
    | '/$orgSlug/projects/$projectId/tasks'
    | '/$orgSlug/projects/$projectId/triage'
    | '/$orgSlug/projects/$projectId'
    | '/$orgSlug/projects/$projectId/conversations/$conversationId'
    | '/$orgSlug/projects/$projectId/conversations/new'
    | '/$orgSlug/projects/$projectId/conversations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/$orgSlug'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/$orgSlug/my-tasks'
    | '/_authenticated/$orgSlug/'
    | '/_authenticated/organizations/'
    | '/_authenticated/$orgSlug/projects/$projectId'
    | '/_authenticated/$orgSlug/projects/$projectId/docs'
    | '/_authenticated/$orgSlug/projects/$projectId/settings'
    | '/_authenticated/$orgSlug/projects/$projectId/tasks'
    | '/_authenticated/$orgSlug/projects/$projectId/triage'
    | '/_authenticated/$orgSlug/projects/$projectId/'
    | '/_authenticated/$orgSlug/projects/$projectId/conversations/$conversationId'
    | '/_authenticated/$orgSlug/projects/$projectId/conversations/new'
    | '/_authenticated/$orgSlug/projects/$projectId/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$orgSlug/': {
      id: '/_authenticated/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/my-tasks': {
      id: '/_authenticated/$orgSlug/my-tasks'
      path: '/my-tasks'
      fullPath: '/$orgSlug/my-tasks'
      preLoaderRoute: typeof AuthenticatedOrgSlugMyTasksRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId': {
      id: '/_authenticated/$orgSlug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$orgSlug/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/': {
      id: '/_authenticated/$orgSlug/projects/$projectId/'
      path: '/'
      fullPath: '/$orgSlug/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/triage': {
      id: '/_authenticated/$orgSlug/projects/$projectId/triage'
      path: '/triage'
      fullPath: '/$orgSlug/projects/$projectId/triage'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdTriageRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/tasks': {
      id: '/_authenticated/$orgSlug/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/$orgSlug/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/settings': {
      id: '/_authenticated/$orgSlug/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/$orgSlug/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/docs': {
      id: '/_authenticated/$orgSlug/projects/$projectId/docs'
      path: '/docs'
      fullPath: '/$orgSlug/projects/$projectId/docs'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdDocsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/conversations/': {
      id: '/_authenticated/$orgSlug/projects/$projectId/conversations/'
      path: '/conversations'
      fullPath: '/$orgSlug/projects/$projectId/conversations/'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/conversations/new': {
      id: '/_authenticated/$orgSlug/projects/$projectId/conversations/new'
      path: '/conversations/new'
      fullPath: '/$orgSlug/projects/$projectId/conversations/new'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdConversationsNewRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
    '/_authenticated/$orgSlug/projects/$projectId/conversations/$conversationId': {
      id: '/_authenticated/$orgSlug/projects/$projectId/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/$orgSlug/projects/$projectId/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedOrgSlugProjectsProjectIdRouteChildren {
  AuthenticatedOrgSlugProjectsProjectIdDocsRoute: typeof AuthenticatedOrgSlugProjectsProjectIdDocsRoute
  AuthenticatedOrgSlugProjectsProjectIdSettingsRoute: typeof AuthenticatedOrgSlugProjectsProjectIdSettingsRoute
  AuthenticatedOrgSlugProjectsProjectIdTasksRoute: typeof AuthenticatedOrgSlugProjectsProjectIdTasksRoute
  AuthenticatedOrgSlugProjectsProjectIdTriageRoute: typeof AuthenticatedOrgSlugProjectsProjectIdTriageRoute
  AuthenticatedOrgSlugProjectsProjectIdIndexRoute: typeof AuthenticatedOrgSlugProjectsProjectIdIndexRoute
  AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute: typeof AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute
  AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute: typeof AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute
  AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute: typeof AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute
}

const AuthenticatedOrgSlugProjectsProjectIdRouteChildren: AuthenticatedOrgSlugProjectsProjectIdRouteChildren =
  {
    AuthenticatedOrgSlugProjectsProjectIdDocsRoute:
      AuthenticatedOrgSlugProjectsProjectIdDocsRoute,
    AuthenticatedOrgSlugProjectsProjectIdSettingsRoute:
      AuthenticatedOrgSlugProjectsProjectIdSettingsRoute,
    AuthenticatedOrgSlugProjectsProjectIdTasksRoute:
      AuthenticatedOrgSlugProjectsProjectIdTasksRoute,
    AuthenticatedOrgSlugProjectsProjectIdTriageRoute:
      AuthenticatedOrgSlugProjectsProjectIdTriageRoute,
    AuthenticatedOrgSlugProjectsProjectIdIndexRoute:
      AuthenticatedOrgSlugProjectsProjectIdIndexRoute,
    AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute:
      AuthenticatedOrgSlugProjectsProjectIdConversationsConversationIdRoute,
    AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute:
      AuthenticatedOrgSlugProjectsProjectIdConversationsNewRoute,
    AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute:
      AuthenticatedOrgSlugProjectsProjectIdConversationsIndexRoute,
  }

const AuthenticatedOrgSlugProjectsProjectIdRouteWithChildren =
  AuthenticatedOrgSlugProjectsProjectIdRoute._addFileChildren(
    AuthenticatedOrgSlugProjectsProjectIdRouteChildren,
  )

interface AuthenticatedOrgSlugRouteChildren {
  AuthenticatedOrgSlugMyTasksRoute: typeof AuthenticatedOrgSlugMyTasksRoute
  AuthenticatedOrgSlugIndexRoute: typeof AuthenticatedOrgSlugIndexRoute
  AuthenticatedOrgSlugProjectsProjectIdRoute: typeof AuthenticatedOrgSlugProjectsProjectIdRouteWithChildren
}

const AuthenticatedOrgSlugRouteChildren: AuthenticatedOrgSlugRouteChildren = {
  AuthenticatedOrgSlugMyTasksRoute: AuthenticatedOrgSlugMyTasksRoute,
  AuthenticatedOrgSlugIndexRoute: AuthenticatedOrgSlugIndexRoute,
  AuthenticatedOrgSlugProjectsProjectIdRoute:
    AuthenticatedOrgSlugProjectsProjectIdRouteWithChildren,
}

const AuthenticatedOrgSlugRouteWithChildren =
  AuthenticatedOrgSlugRoute._addFileChildren(AuthenticatedOrgSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOrgSlugRoute: typeof AuthenticatedOrgSlugRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrgSlugRoute: AuthenticatedOrgSlugRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
